MDScreen:
    name: "Splash"
    id: splash_screen

    MDFloatLayout:
        md_bg_color: app.theme_cls.backgroundColor
        size_hint: 1, 1
        FitImage:
            id: splash_image

            pos_hint: {"center_x": .5, "center_y": .5}
            size_hint: .95, .95
            source: "splash.jpg"
            pos_hint: {"top": 1}
            fit_mode: "scale-down"
            radius: "20dp", "20dp", "20dp", "20dp"

